version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  key-generator:
    build: 
      dockerfile: ./key-generator.dockerfile
    networks:
      - app-tier
    environment:
      - ENV_FOR_DYNACONF=container
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - create-dynamodb-table
      - dynamodb
      - redis

  create-dynamodb-table:
    build:
      dockerfile: ./create-table.dockerfile
    networks:
      - app-tier
    environment:
      - ENV_FOR_DYNACONF=container
    depends_on:
      - dynamodb

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-tier