version: '3.8'

services:
  app:
    build:
      dockerfile: ./app.dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV_FOR_DYNACONF=container
    depends_on:
      - key-generator
      - create-dynamodb-table
      - dynamodb
      - redis

  key-generator:
    build: 
      dockerfile: ./key-generator.dockerfile
    environment:
      - ENV_FOR_DYNACONF=container
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - create-dynamodb-table
      - dynamodb
      - redis

  create-dynamodb-table:
    build:
      dockerfile: ./create-table.dockerfile
    environment:
      - ENV_FOR_DYNACONF=container
    depends_on:
      - dynamodb

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"